### ISSUE TITLE
[Bug]: strange behavior with ad astra

### ISSUE THREAD

**Issue by Nicodemus111** [Fuzss/airhop#12]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.8

### Notes (Required)

when i land after jumping with air hop it does not replenish my air hop jumps with ad astra 1.15.3 installed. it only replenishes when i fall far enough to take fall damage, this is all in the overworld and i have not tested this on ad astra planets.

to reproduce:
install air hop
install ad astra and its dependencies
use all of your air hop charges and land without taking fall damage
you will not regain air hop charges

**Comment by OodlyNoodly** [comment]
noticed this with Artifacts too when wearing the Bunny Hoppers which cancels fall damage and gives jumpboost 2. so might have something to do with taking fall damage?

**Comment by Fuzss** [comment]
Fixed for 1.20.1+.
