### ISSUE TITLE
[Bug]: client Crash during Startup [possibly incompatible mods]

### ISSUE THREAD

**Issue by MysticaIl** [Fuzss/airhop#14]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

**Current Behavior:**- Client Crash during startup, when using Majruzs Library and peculiar pieces mod

**Fabric Version:-** 1.15.0

**Steps to replicate:**- Start up Minecraft Fabric 1.20.1 version 1.15.0, add airhop mod, Majurzs Lib and peculiar pieces

**Expected Behavior:-** Normal Launch

**List of used mods:-** Fabric API 0.91.0
                                Forge Config API port
                                Majurzs Lib
                                Puzzles Lib
                                Peculiar Pieces
                                Air hop
                                Patchouli
                                Trinkets

### latest.log (Optional)

https://gist.github.com/MysticaIl/d0df4472b883133dbe9798e21e048f69

### Crash Report

https://gist.github.com/MysticaIl/3a22f6765147794bf2a89180cf6077be

**Comment by MysticaIl** [comment]
I add crash report?

**Comment by Fuzss** [comment]
yeah i need that, the log doesn't have anything important

**Comment by MysticaIl** [comment]
I tested it with other mods like, Enderzoology, Spiky Spikes, Hang glider etc. They seem to not work properly aswell as puzzles lib when paired with these 2 mods (Peculiar pieces and Majurzs Lib)

**Comment by Fuzss** [comment]
I need a crash report.

**Comment by MysticaIl** [comment]
https://gist.github.com/MysticaIl/3a22f6765147794bf2a89180cf6077be  (airhop crash)

https://gist.github.com/MysticaIl/fe0400be3b7d8adf6d6710be1fa840c3  (Puzzles Lib crash)

**Comment by Fuzss** [comment]
Thanks, that's an issue from Peculiar Pieces and has nothing to do with Puzzles Lib. Puzzles Lib is just the first mod to 'uncover' the error.

**Comment by MysticaIl** [comment]
Ok thank you.
