### ISSUE TITLE
[Crash]: NPE on AirHopsCapability.resetAirHops()

### ISSUE THREAD

**Issue by mahjerion** [Fuzss/airhop#15]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.1

### Other Mods Involved (Required)

No

### Notes (Required)

Not exactly sure what causes it, but it happened on death.

### Crash Report (Required)

https://gist.github.com/mahjerion/35064ef3fd662c52bb51c1e4c0dee9bc

**Comment by Fuzss** [comment]
Thanks, fixed in v8.0.2.
