### ISSUE TITLE
Issue with the Slow Falling effect

### ISSUE THREAD

**Issue by sasasasara** [Fuzss/airhop#8]
> **Affected Versions**:
> 
> * **airhop**: armorplus-1.12.2-11.20.0.56
> * **Minecraft**: 1.16.5
> * **Forge**: 1.16.5-36.2.23
> * (Optional) ArmorPlus: 16.6.0

> **Affected Side (Client or Server)**:
> 
> * [x]  Client
> * [x]  Server
 
> **What happens**: Your hops don't reset if you have the Slow Falling effect, as if you aren't ever touching the ground after your first hops. I'm using the Ender Dragon armor from the ArmorPlus mod, which gives you permanent Slow Falling.

> **What you expected to happen:**: The hops to reset, regardless of active status effects.

**Comment by sasasasara** [comment]
I'm no Java programmer, but my theory is that [this line](https://github.com/Fuzss/airhop/blob/853986c70808afe6af44112cb61ecf37826ce528/src/main/java/com/fuzs/airhop/element/AirHopElement.java#L172) is causing the issue.

`        boolean isPerformingAction = player.isPassenger() || player.abilities.isFlying || player.isOnLadder();`

I suspect that having Slow Falling makes player.abilities.isFlying true.

**Comment by Fuzss** [comment]
Thanks for the report! Fixed in v3.1.1.
